#import "_MNLLayerObservingPropertyName.h"


FOUNDATION_EXTERN const _MNLLayerObservingPropertyName _MNLGradientLayerObservingColorsPropertyName;
FOUNDATION_EXTERN const _MNLLayerObservingPropertyName _MNLGradientLayerObservingLocationsPropertyName;
FOUNDATION_EXTERN const _MNLLayerObservingPropertyName _MNLGradientLayerObservingEndPointPropertyName;
FOUNDATION_EXTERN const _MNLLayerObservingPropertyName _MNLGradientLayerObservingStartPointPropertyName;
FOUNDATION_EXTERN const _MNLLayerObservingPropertyName _MNLGradientLayerObservingTypePropertyName;
