@import Foundation;


typedef NSString *_MNLLayerObservingPropertyName NS_STRING_ENUM;

FOUNDATION_EXTERN const _MNLLayerObservingPropertyName _MNLLayerObservingBackgroundColorPropertyName;
FOUNDATION_EXTERN const _MNLLayerObservingPropertyName _MNLLayerObservingBorderColorPropertyName;
FOUNDATION_EXTERN const _MNLLayerObservingPropertyName _MNLLayerObservingBorderWidthPropertyName;
FOUNDATION_EXTERN const _MNLLayerObservingPropertyName _MNLLayerObservingCornerRadiusPropertyName;
FOUNDATION_EXTERN const _MNLLayerObservingPropertyName _MNLLayerObservingFramePropertyName;
FOUNDATION_EXTERN const _MNLLayerObservingPropertyName _MNLLayerObservingShadowColorPropertyName;
FOUNDATION_EXTERN const _MNLLayerObservingPropertyName _MNLLayerObservingShadowOffsetPropertyName;
FOUNDATION_EXTERN const _MNLLayerObservingPropertyName _MNLLayerObservingShadowOpacityPropertyName;
FOUNDATION_EXTERN const _MNLLayerObservingPropertyName _MNLLayerObservingShadowPathPropertyName;
FOUNDATION_EXTERN const _MNLLayerObservingPropertyName _MNLLayerObservingShadowRadiusPropertyName;
